### ISSUE TITLE
how do i open it in csgo

### ISSUE THREAD

**Issue by hyender** [monthyx1337/GamSensFinal#2]

**Comment by dagadtwok** [comment]
lmao press insert

**Comment by hyender** [comment]
but i dont know how to open the program because its a .h file and i dont know how to open it

**Comment by morganwall** [comment]
It's a project, build it in an IDE. If you don't understand that, then fuck off.

**Comment by LilSizzurp** [comment]
1) download Visual Studio (i recommend 2019 preview)
2) open the .sln
3) build
4) inject into csgo
5) pressed insert
6) you are good to go now you are b1g hacker man
